-- QR Studio database + auth bootstrap
-- Apply this in Supabase SQL Editor or via Supabase migrations.

create extension if not exists pgcrypto;

create table if not exists public.tenants (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'My company',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.memberships (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'owner',
  created_at timestamptz not null default now(),
  unique (tenant_id, user_id)
);

create table if not exists public.branding (
  tenant_id uuid primary key references public.tenants(id) on delete cascade,
  company_name text,
  primary_color text not null default '#111111',
  background_color text not null default '#ffffff',
  accent_color text not null default '#6366f1',
  logo_url text,
  custom_domain text unique,
  domain_status text not null default 'none',
  domain_verified_at timestamptz,
  domain_cf_id text,
  updated_at timestamptz not null default now()
);

create table if not exists public.qr_codes (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  created_by uuid references auth.users(id) on delete set null,
  title text not null default 'Untitled QR',
  type text not null default 'url',
  content text,
  is_dynamic boolean not null default false,
  short_code text unique,
  destination text,
  design jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.scans (
  id bigint generated by default as identity primary key,
  qr_id uuid not null references public.qr_codes(id) on delete cascade,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  ip text,
  country text,
  device text,
  os text,
  browser text,
  referer text,
  user_agent text,
  scanned_at timestamptz not null default now()
);

create index if not exists memberships_user_id_idx on public.memberships(user_id);
create index if not exists memberships_tenant_id_idx on public.memberships(tenant_id);
create index if not exists qr_codes_tenant_id_idx on public.qr_codes(tenant_id);
create index if not exists qr_codes_short_code_idx on public.qr_codes(short_code);
create index if not exists scans_qr_id_scanned_at_idx on public.scans(qr_id, scanned_at desc);
create index if not exists scans_tenant_id_scanned_at_idx on public.scans(tenant_id, scanned_at desc);

create or replace function public.is_tenant_member(p_tenant_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.memberships m
    where m.tenant_id = p_tenant_id
      and m.user_id = auth.uid()
  );
$$;

alter table public.tenants enable row level security;
alter table public.memberships enable row level security;
alter table public.branding enable row level security;
alter table public.qr_codes enable row level security;
alter table public.scans enable row level security;

drop policy if exists tenants_select_member on public.tenants;
create policy tenants_select_member on public.tenants
  for select using (public.is_tenant_member(id));

drop policy if exists memberships_select_self on public.memberships;
create policy memberships_select_self on public.memberships
  for select using (user_id = auth.uid());

drop policy if exists branding_select_member on public.branding;
create policy branding_select_member on public.branding
  for select using (public.is_tenant_member(tenant_id));

drop policy if exists branding_insert_member on public.branding;
create policy branding_insert_member on public.branding
  for insert with check (public.is_tenant_member(tenant_id));

drop policy if exists branding_update_member on public.branding;
create policy branding_update_member on public.branding
  for update using (public.is_tenant_member(tenant_id))
  with check (public.is_tenant_member(tenant_id));

drop policy if exists qr_codes_select_member on public.qr_codes;
create policy qr_codes_select_member on public.qr_codes
  for select using (public.is_tenant_member(tenant_id));

drop policy if exists qr_codes_insert_member on public.qr_codes;
create policy qr_codes_insert_member on public.qr_codes
  for insert with check (public.is_tenant_member(tenant_id) and created_by = auth.uid());

drop policy if exists qr_codes_update_member on public.qr_codes;
create policy qr_codes_update_member on public.qr_codes
  for update using (public.is_tenant_member(tenant_id))
  with check (public.is_tenant_member(tenant_id));

drop policy if exists qr_codes_delete_member on public.qr_codes;
create policy qr_codes_delete_member on public.qr_codes
  for delete using (public.is_tenant_member(tenant_id));

drop policy if exists scans_select_member on public.scans;
create policy scans_select_member on public.scans
  for select using (public.is_tenant_member(tenant_id));

create or replace function public.bootstrap_user_workspace(
  p_user_id uuid,
  p_email text,
  p_company_name text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant_id uuid;
  v_company_name text;
begin
  select m.tenant_id
    into v_tenant_id
    from public.memberships m
    where m.user_id = p_user_id
    limit 1;

  if v_tenant_id is not null then
    return v_tenant_id;
  end if;

  v_company_name := nullif(trim(coalesce(p_company_name, '')), '');
  if v_company_name is null then
    v_company_name := nullif(split_part(coalesce(p_email, ''), '@', 1), '');
  end if;
  if v_company_name is null then
    v_company_name := 'My company';
  end if;

  insert into public.tenants (name, created_by)
  values (v_company_name, p_user_id)
  returning id into v_tenant_id;

  insert into public.memberships (tenant_id, user_id, role)
  values (v_tenant_id, p_user_id, 'owner')
  on conflict (tenant_id, user_id) do nothing;

  insert into public.branding (
    tenant_id,
    company_name,
    primary_color,
    background_color,
    accent_color,
    domain_status
  )
  values (
    v_tenant_id,
    v_company_name,
    '#111111',
    '#ffffff',
    '#6366f1',
    'none'
  )
  on conflict (tenant_id) do nothing;

  return v_tenant_id;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.bootstrap_user_workspace(
    new.id,
    new.email,
    new.raw_user_meta_data ->> 'company_name'
  );

  if to_regprocedure('public.link_platform_admin_for_user(uuid,text)') is not null then
    perform public.link_platform_admin_for_user(new.id, new.email);
  end if;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.ensure_user_tenant()
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_email text;
  v_company_name text;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  select u.email, u.raw_user_meta_data ->> 'company_name'
    into v_email, v_company_name
    from auth.users u
    where u.id = v_user_id;

  if v_email is null then
    raise exception 'User not found';
  end if;

  return public.bootstrap_user_workspace(v_user_id, v_email, v_company_name);
end;
$$;

drop function if exists public.qr_analytics(uuid);

create function public.qr_analytics(p_qr uuid)
returns table (
  total bigint,
  last_7 bigint,
  by_day jsonb,
  by_device jsonb
)
language sql
security definer
set search_path = public
stable
as $$
  with target as (
    select q.id, q.tenant_id
    from public.qr_codes q
    where q.id = p_qr
      and public.is_tenant_member(q.tenant_id)
  ),
  scan_rows as (
    select s.*
    from public.scans s
    join target t on t.id = s.qr_id
  ),
  day_rows as (
    select to_char(s.scanned_at::date, 'YYYY-MM-DD') as day, count(*) as n
    from scan_rows s
    where s.scanned_at >= now() - interval '30 days'
    group by s.scanned_at::date
  ),
  device_rows as (
    select coalesce(device, 'Unknown') as device, count(*) as n
    from scan_rows
    group by coalesce(device, 'Unknown')
  )
  select
    (select count(*) from scan_rows)::bigint as total,
    (select count(*) from scan_rows where scanned_at >= now() - interval '7 days')::bigint as last_7,
    coalesce((select jsonb_object_agg(day, n order by day) from day_rows), '{}'::jsonb) as by_day,
    coalesce((select jsonb_object_agg(device, n order by device) from device_rows), '{}'::jsonb) as by_device;
$$;

revoke all on function public.bootstrap_user_workspace(uuid, text, text) from public;
grant execute on function public.ensure_user_tenant() to authenticated;
grant execute on function public.qr_analytics(uuid) to authenticated;

insert into storage.buckets (id, name, public)
values ('logos', 'logos', true), ('files', 'files', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists storage_select_member_files on storage.objects;
create policy storage_select_member_files on storage.objects
  for select using (bucket_id in ('logos', 'files'));

drop policy if exists storage_insert_member_files on storage.objects;
create policy storage_insert_member_files on storage.objects
  for insert with check (
    bucket_id in ('logos', 'files')
    and public.is_tenant_member((storage.foldername(name))[1]::uuid)
  );

drop policy if exists storage_update_member_files on storage.objects;
create policy storage_update_member_files on storage.objects
  for update using (
    bucket_id in ('logos', 'files')
    and public.is_tenant_member((storage.foldername(name))[1]::uuid)
  )
  with check (
    bucket_id in ('logos', 'files')
    and public.is_tenant_member((storage.foldername(name))[1]::uuid)
  );
